FROM golang:1.20-alpine3.17

WORKDIR /opt

RUN mkdir -p github.com/jbullfrog81/fishing-buddy-service

WORKDIR /opt/github.com/jbullfrog81/fishing-buddy-service

COPY go.mod ./
COPY go.sum ./
RUN go mod download

COPY cmd/main.go ./
ADD internal ./internal/

RUN go build -o /bin/fishing-buddy -v .

EXPOSE 8080

ENTRYPOINT [ "fishing-buddy" ]